### ISSUE TITLE
MLGT: Some Danish concepts use outdated English Term IDs

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/TMG#2]
Some concepts are provided in other languages but without a counterpart in English. These may have been unsynchronized in translation.

For example, the term "compound coordinate reference system" is listed in English as ID 702, but in Danish ID 59. This means the concept page for "compound coordinate reference system" will not have Danish, and the Term ID 59 page will only be in Danish.

We need to enforce and fix all these issues.

**Comment by ronaldtse** [comment]
Specifically these are the funny ones:

```yaml
59:
  term: sammensat koordinatsystem
  id: 59
  dan:
    id: 59
    term: sammensat koordinatsystem
    definition: koordinatsystem, der anvender to andre uafhængige koordinatsystemer
      til at beskrive en position
    language_code: dan
    notes: []
    examples:
    - EKSEMPEL - Et koordinatsystem baseret på et to- eller tredimensionalt koordinatsystem
      og et andet referencesystem baseret på et tyngdekraftrelateret højdesystem.
    authoritative_source: ISO 19111:2007
    date_accepted: 2007-07-01 00:00:00.000000000 +08:00
    release: '1'
65:
  term: begreber, harmonisering af
  id: 65
  dan:
    id: 65
    term: begreber, harmonisering af
    definition: det at reducere eller eliminere mindre forskelle mellem to eller flere
      begreber, der allerede er tæt forbundet med hinanden
    language_code: dan
    notes: []
    examples: []
    authoritative_source: ISO 860:1996
    release: '1'
89:
  term: koordinatkonvertering
  id: 89
  dan:
    id: 89
    term: koordinatkonvertering
    definition: ændring af koordinater baseret på en 1 til 1-relation fra et koordinatsystem
      til et andet baseret på samme datum
    language_code: dan
    notes:
    - NOTE – Ved en koordinatkonvertering anvendes parametre med konstante værdier.
    examples:
    - EKSEMPEL - Mellem geodætiske og kartesiske koordinatsystemer, eller mellem geodætiske
      og projicerede koordinater, eller ændring af enheder fx fra radianer til grader
      eller fra fod til meter.
    authoritative_source: ISO 19111:2007
    date_accepted: 2007-07-01 00:00:00.000000000 +08:00
    release: '1'
92:
  term: koordinatreferencesystem
  id: 92
  dan:
    id: 92
    term: koordinatreferencesystem
    definition: koordinatsystem, der er relateret til et datum i den virkelige verden
    language_code: dan
    notes:
    - NOTE – For geodætiske og vertikale datummer vil koordinatsystemet blive relateret
      til jorden.
    examples: []
    authoritative_source: ISO 19111:2007
    date_accepted: 2007-07-01 00:00:00.000000000 +08:00
    release: '1'
94:
  term: koordinattransformation
  id: 94
  dan:
    id: 94
    term: koordinattransformation
    definition: ændring af koordinater fra et koordinatsystem til et andet koordinatsystem
      baseret på et andet datum i en 1 til 1-relation
    language_code: dan
    notes:
    - NOTE – Ved en koordinattransformation anvendes parametre, der er afledt empirisk
      af en mængde af punkter med kendte koordinater i begge koordinatsystemer.
    examples: []
    authoritative_source: ISO 19111:2007
    date_accepted: 2007-07-01 00:00:00.000000000 +08:00
    release: '1'
126:
  term: datum
  id: 126
  dan:
    id: 126
    term: datum
    definition: parameter eller sæt af parametre, der tjener som reference eller grundlag
      for beregning af andre parametre
    language_code: dan
    notes:
    - NOTE – Et datum definerer positionen af nulpunkt, målestok og orientering af
      akserne i et koordinatsystem.
    examples: []
    authoritative_source: ISO 19111:2007
    date_accepted: 2007-07-01 00:00:00.000000000 +08:00
    release: '1'
172:
  term: featurekatalog
  id: 172
  dan:
    id: 172
    term: featurekatalog
    definition: katalog, der indeholder definitioner og beskrivelser af featuretyper,
      featureattributter og featureassociationer, som optræder i et eller flere geografiske
      datasæt sammen med de eventuelle featureoperationer, der kan anvendes
    language_code: dan
    notes: []
    examples: []
    authoritative_source: ISO 19101:2002
    date_accepted: 2002-07-01 00:00:00.000000000 +08:00
    release: '1'
198:
  term: geodætisk datum
  id: 198
  dan:
    id: 198
    term: geodætisk datum
    definition: datum, der beskriver relationen mellem et koordinatsystem og jorden
    language_code: dan
    notes:
    - NOTE – I de fleste tilfælde indeholder det geodætiske datum en ellipsoidedefinition.
    examples: []
    authoritative_source: ISO 19111:2007
    date_accepted: 2007-07-01 00:00:00.000000000 +08:00
    release: '1'
208:
  term: geoide
  id: 208
  dan:
    id: 208
    term: geoide
    definition: plan overflade, der bedst passer til havenes middelvandstand enten
      lokalt eller globalt
    language_code: dan
    notes:
    - NOTE – "Plan overflade" betyder en ækvipotential flade i jordens tyngdefelt,
      der overalt er vinkelret på tyngdekraftens retning.
    examples: []
    authoritative_source: ISO 19111:2007
    date_accepted: 2007-07-01 00:00:00.000000000 +08:00
    release: '1'
226:
  term: højde
  id: 226
  dan:
    id: 226
    term: højde
    abbrev: h eller H
    definition: et punkts afstand fra en valgt referenceoverflade langs en linje,
      der er vinkelret på denne overflade
    language_code: dan
    notes:
    - NOTE – Se ellipsoidehøjde og tyngderelateret højde.
    - NOTE 2 – Højde af et punkt uden for overfladen regnes positiv; negativ højde
      kaldes også dybde.
    examples: []
    authoritative_source: ISO 19111:2007
    date_accepted: 2007-07-01 00:00:00.000000000 +08:00
    release: '1'
227:
  term: hierarkisk register
  id: 227
  dan:
    id: 227
    term: hierarkisk register
    definition: struktureret sæt af registre for et domæne af registerelementer, bestående
      af et hovedregister og et sæt af delregistre
    language_code: dan
    notes: []
    examples:
    - EKSEMPEL - ISO 6523 er associeret med et hierarkisk register. Hovedregisteret
      indeholder skemaer for identifikation af organisation -  og hvert delregister
      indeholder et sæt af organisationsidentifikatorer, der er i overensstemmelse
      med et enkelt skema for identifikation af organisation.
    authoritative_source: ISO 19135:2005
    date_accepted: 2005-10-15 00:00:00.000000000 +08:00
    release: '1'
168:
  term: objeto geográfico (feature)
  id: 168
  spa:
    id: 168
    term: objeto geográfico (feature)
    alt: fenómeno
    definition: abstracción de un fenómeno del mundo real
    country_code: PA, CU, CO, CL, BO, MX, EC, SV, UY, AR
    language_code: spa
    notes:
    - NOTA  Un objeto geográfico puede darse como un tipo o como una instancia. Debe
      usarse tipo de objeto geográfico o instancia de objeto geográfico sólo cuando
      se desea referirse a uno de ellos.
    examples: []
    entry_status: notValid
    authoritative_source: ISO 19101-1:2014, 4.1.11
    lineage_source: ISO 19101:2002
    lineage_source_similarity: '1'
    date_accepted: 2002-07-01 00:00:00.000000000 +08:00
    review_date: 2010-10-12 00:00:00.000000000 +08:00
    review_status: final
    review_decision: accepted
    review_decision_date: 2014-11-01
    review_decision_event: Publication of ISO 19101-1:2014
    review_decision_notes: Authoritative reference changed from ISO 19101:2002 to
      ISO 19101-1:2014. Lineage source added as ISO 19101:2002.
    release: '1'

```
